[E 140218 08:51:12 web:1228] Uncaught exception GET /queries?queries=15 (10.0.3.3)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='10.0.3.3', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 505, in run
        yielded = self.gen.throw(*exc_info)
      File "server.py", line 66, in get
        for _ in xrange(queries)]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 496, in run
        next = self.yield_point.get_result()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 426, in get_result
        return [i.get_result() for i in self.children]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/motor-0.1.2-py2.7.egg/motor/__init__.py", line 1969, in get_result
        raise error
    AutoReconnect: could not connect to 10.0.3.5:27017: timed out
[E 140218 08:51:12 web:1228] Uncaught exception GET /queries?queries=15 (10.0.3.3)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='10.0.3.3', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 505, in run
        yielded = self.gen.throw(*exc_info)
      File "server.py", line 66, in get
        for _ in xrange(queries)]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 496, in run
        next = self.yield_point.get_result()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 426, in get_result
        return [i.get_result() for i in self.children]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/motor-0.1.2-py2.7.egg/motor/__init__.py", line 1969, in get_result
        raise error
    AutoReconnect: could not connect to 10.0.3.5:27017: timed out
[E 140218 08:51:12 web:1635] 500 GET /queries?queries=15 (10.0.3.3) 20034.02ms
[E 140218 08:51:12 web:1228] Uncaught exception GET /queries?queries=15 (10.0.3.3)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='10.0.3.3', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 505, in run
        yielded = self.gen.throw(*exc_info)
      File "server.py", line 66, in get
        for _ in xrange(queries)]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 496, in run
        next = self.yield_point.get_result()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 426, in get_result
        return [i.get_result() for i in self.children]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/motor-0.1.2-py2.7.egg/motor/__init__.py", line 1969, in get_result
        raise error
    AutoReconnect: could not connect to 10.0.3.5:27017: timed out
[E 140218 08:51:12 web:1228] Uncaught exception GET /queries?queries=15 (10.0.3.3)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='10.0.3.3', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 505, in run
        yielded = self.gen.throw(*exc_info)
      File "server.py", line 66, in get
        for _ in xrange(queries)]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 496, in run
        next = self.yield_point.get_result()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 426, in get_result
        return [i.get_result() for i in self.children]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/motor-0.1.2-py2.7.egg/motor/__init__.py", line 1969, in get_result
        raise error
    AutoReconnect: could not connect to 10.0.3.5:27017: timed out
[E 140218 08:51:12 web:1635] 500 GET /queries?queries=15 (10.0.3.3) 20033.82ms
[E 140218 08:51:12 web:1228] Uncaught exception GET /queries?queries=15 (10.0.3.3)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='10.0.3.3', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 505, in run
        yielded = self.gen.throw(*exc_info)
      File "server.py", line 66, in get
        for _ in xrange(queries)]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 496, in run
        next = self.yield_point.get_result()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 426, in get_result
        return [i.get_result() for i in self.children]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/motor-0.1.2-py2.7.egg/motor/__init__.py", line 1969, in get_result
        raise error
    AutoReconnect: could not connect to 10.0.3.5:27017: timed out
[E 140218 08:51:12 web:1228] Uncaught exception GET /queries?queries=15 (10.0.3.3)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='10.0.3.3', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 505, in run
        yielded = self.gen.throw(*exc_info)
      File "server.py", line 66, in get
        for _ in xrange(queries)]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 496, in run
        next = self.yield_point.get_result()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 426, in get_result
        return [i.get_result() for i in self.children]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/motor-0.1.2-py2.7.egg/motor/__init__.py", line 1969, in get_result
        raise error
    AutoReconnect: could not connect to 10.0.3.5:27017: timed out
[E 140218 08:51:12 web:1635] 500 GET /queries?queries=15 (10.0.3.3) 20033.18ms
[E 140218 08:51:12 web:1635] 500 GET /queries?queries=15 (10.0.3.3) 20024.57ms
[E 140218 08:51:12 web:1635] 500 GET /queries?queries=15 (10.0.3.3) 20034.23ms
[E 140218 08:51:12 web:1635] 500 GET /queries?queries=15 (10.0.3.3) 20028.78ms
[E 140218 08:51:12 web:1635] 500 GET /queries?queries=15 (10.0.3.3) 20036.05ms
[E 140218 08:51:12 web:1228] Uncaught exception GET /queries?queries=15 (10.0.3.3)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='10.0.3.3', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 505, in run
        yielded = self.gen.throw(*exc_info)
      File "server.py", line 66, in get
        for _ in xrange(queries)]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 496, in run
        next = self.yield_point.get_result()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 426, in get_result
        return [i.get_result() for i in self.children]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/motor-0.1.2-py2.7.egg/motor/__init__.py", line 1969, in get_result
        raise error
    AutoReconnect: could not connect to 10.0.3.5:27017: timed out
[E 140218 08:51:12 web:1635] 500 GET /queries?queries=15 (10.0.3.3) 20028.48ms
[E 140218 08:51:12 web:1228] Uncaught exception GET /queries?queries=15 (10.0.3.3)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='10.0.3.3', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 505, in run
        yielded = self.gen.throw(*exc_info)
      File "server.py", line 66, in get
        for _ in xrange(queries)]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 496, in run
        next = self.yield_point.get_result()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 426, in get_result
        return [i.get_result() for i in self.children]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/motor-0.1.2-py2.7.egg/motor/__init__.py", line 1969, in get_result
        raise error
    AutoReconnect: could not connect to 10.0.3.5:27017: timed out
[E 140218 08:51:12 web:1635] 500 GET /queries?queries=15 (10.0.3.3) 20026.64ms
[E 140218 08:51:12 web:1228] Uncaught exception GET /queries?queries=15 (10.0.3.3)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='10.0.3.3', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 505, in run
        yielded = self.gen.throw(*exc_info)
      File "server.py", line 66, in get
        for _ in xrange(queries)]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 496, in run
        next = self.yield_point.get_result()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 426, in get_result
        return [i.get_result() for i in self.children]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/motor-0.1.2-py2.7.egg/motor/__init__.py", line 1969, in get_result
        raise error
    AutoReconnect: could not connect to 10.0.3.5:27017: timed out
[E 140218 08:51:12 web:1635] 500 GET /queries?queries=15 (10.0.3.3) 20037.62ms
[E 140218 08:51:12 web:1228] Uncaught exception GET /queries?queries=15 (10.0.3.3)
    HTTPRequest(protocol='http', host='localhost', method='GET', uri='/queries?queries=15', version='HTTP/1.1', remote_ip='10.0.3.3', headers={'Host': 'localhost', 'Connection': 'keep-alive', 'Accept': 'application/json,text/html;q=0.9,application/xhtml+xml;q=0.9,application/xml;q=0.8,*/*;q=0.7'})
    Traceback (most recent call last):
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/web.py", line 1144, in _when_complete
        if result.result() is not None:
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/concurrent.py", line 129, in result
        raise_exc_info(self.__exc_info)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/stack_context.py", line 302, in wrapped
        ret = fn(*args, **kwargs)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 550, in inner
        self.set_result(key, result)
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 476, in set_result
        self.run()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 505, in run
        yielded = self.gen.throw(*exc_info)
      File "server.py", line 66, in get
        for _ in xrange(queries)]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 496, in run
        next = self.yield_point.get_result()
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/tornado-3.1-py2.7.egg/tornado/gen.py", line 426, in get_result
        return [i.get_result() for i in self.children]
      File "/home/techempower/FrameworkBenchmarks/installs/py2/lib/python2.7/site-packages/motor-0.1.2-py2.7.egg/motor/__init__.py", line 1969, in get_result
        raise error
    AutoReconnect: could not connect to 10.0.3.5:27017: timed out
[E 140218 08:51:12 web:1635] 500 GET /queries?queries=15 (10.0.3.3) 20042.90ms
